# Generated by Django 6.0.6 on 2026-06-28 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Barcode Category',
                'verbose_name_plural': 'Barcode Categories',
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': '7. BOM',
            },
        ),
        migrations.CreateModel(
            name='MovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('product', 'Product')], max_length=50)),
                ('item_id', models.IntegerField()),
                ('from_location', models.CharField(choices=[('raw_material', 'Raw Material'), ('production_line', 'Production Line'), ('finished_goods', 'Finished Goods')], max_length=50)),
                ('to_location', models.CharField(choices=[('raw_material', 'Raw Material'), ('production_line', 'Production Line'), ('finished_goods', 'Finished Goods')], max_length=50)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Movement Log',
                'verbose_name_plural': '14. Movement Logs',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('etin', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('incorporartion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': '1. Organizations',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': '6. Raw Materials',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': '5. Suppliers',
            },
        ),
        migrations.CreateModel(
            name='BarcodedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('product_location', models.CharField(default='Shelf', max_length=1024)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ics.barcodecategory')),
            ],
            options={
                'verbose_name': 'Barcoded Product',
                'verbose_name_plural': 'Barcoded Products',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('warehouse', 'Warehouse')], max_length=50)),
                ('address', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.organization')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': '2. Locations',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.bom')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': '9. Products',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product_quantity', models.FloatField()),
                ('production_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.product')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': '12. Productions',
            },
        ),
        migrations.CreateModel(
            name='ProductionRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.production')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.rawmaterial')),
            ],
            options={
                'verbose_name': 'Production Raw Material',
                'verbose_name_plural': '13. Production Raw Materials',
            },
        ),
        migrations.AddField(
            model_name='production',
            name='raw_materials_used',
            field=models.ManyToManyField(through='ics.ProductionRawMaterial', to='ics.rawmaterial'),
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.bom')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.rawmaterial')),
            ],
            options={
                'verbose_name': 'BOM Item',
                'verbose_name_plural': '8. BOM Items',
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='raw_materials',
            field=models.ManyToManyField(through='ics.BOMItem', to='ics.rawmaterial'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.location')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': '3. Rooms',
            },
        ),
        migrations.CreateModel(
            name='StorageSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.room')),
            ],
            options={
                'verbose_name': 'Storage Spot',
                'verbose_name_plural': '4. Storage Spots',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.rawmaterial')),
                ('storage_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.storagespot')),
            ],
            options={
                'verbose_name': 'Raw Material Inventory',
                'verbose_name_plural': '10. Raw Material Inventories',
            },
        ),
        migrations.CreateModel(
            name='FinishedProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.product')),
                ('storage_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.storagespot')),
            ],
            options={
                'verbose_name': 'Finished Product Inventory',
                'verbose_name_plural': '11. Finished Product Inventories',
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.supplier'),
        ),
    ]
